### PR TITLE
Support ephemeralStorage

### PR DESCRIPTION
**Pull request by shoot16625**
## What

- supports ECS tasks with ephemeralStorage
- ref:
  - [AWS::ECS::TaskDefinition EphemeralStorage](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-ephemeralstorage.html#cfn-ecs-taskdefinition-ephemeralstorage-sizeingib)
  - [size_in_gi_b value is correct](https://stackoverflow.com/questions/67607006/how-to-configure-ephemeral-storage-on-ecs-fargate-task-via-ruby-sdk), not `size_in_gib`
  - ※ Implemented with reference to `logConfiguration`

### CODE REVIEW

**Comment by civitaspo** [comment]
@shoot16625 I fixed the CI in https://github.com/civitaspo/digdag-operator-ecs_task/pull/81, so could you rebase this branch?

**Comment by shoot16625** [comment]
Thank you for your announcement, and I rebased this branch.

**Comment by civitaspo** [comment]
@shoot16625 I can't seem to compile it, so please fix it.

**Comment by shoot16625** [comment]
I passed local test!
Ephemeral Storage needed `aws-java-sdk version up`.

**Comment by civitaspo** [comment]
shipped https://github.com/civitaspo/digdag-operator-ecs_task/releases/tag/0.1.4

**Pull request merged**
