### PR TITLE
Supports CapacityProvider

### PR DESCRIPTION
**Pull request by hiro-o918**
## What
- supports ECS tasks with capacity provider strategy
- ref: 
  - [CapacityProviderStrategy](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CapacityProviderStrategyItem.html)
  - [CapacityProvider](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CapacityProvider.html)

### CODE REVIEW

**Comment by civitaspo** [comment]
Please wait as I read the documentation for the Capacity Provider.

**Comment by civitaspo** [comment]
Looks good to me.

**Comment by civitaspo** [comment]
https://github.com/civitaspo/digdag-operator-ecs_task/releases/tag/0.1.2 Shipped

**Comment by hiro-o918** [comment]
thank you!

**Pull request merged**
